name: nevmet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_strategy: ^0.2.0
  responsive_builder: ^0.7.0
  flutter_animate: ^4.1.1+1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  xml: ^6.5.0
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

   # To add assets to your application, add an assets section, like this:
   #these files go to web/assets not build. they move to build after flutter build run makes a copy to bild output
  assets:
    - web/assets/background.jpg
    - web/assets/nevm_logo.png
    - web/assets/WebData.xml
    - web/assets/red_rock.jpg
    - web/assets/center.jpg
    - web/assets/dragon.jpg
    - web/assets/dragon2.jpg

    - web/assets/BBC.png
    - web/assets/PHYSORG.png
    - web/assets/scitechdaily.jpg
    - web/assets/sd.png
